#finding out RNA transcript from a DNA sequence

dnaseq = '''CTTTTCTTTAGTGTTTTGACTAATAATTGGTCAAGCCTACCATTACAAACTATGTTCC
ATTACCAGTACAGAGCACATGGTTTCACTTTTTAACCAAGCAACTTTATCTTAAACTTGCTTATCAAGAA
CTGTCTCTTCGGTAACACAAAAGGGTCTTTTATCAAAACCTATATATAGGATACTTTTCATAATTGGAGT
AAGATCTACAAA
ACAGAGAGTTGTATACTTTAAATCATTTAGAGGTTGTGAAATATTATGGAGAGTGAAGGAAAGATTGTGT
TCACAGAAGAGCAAGAGGCTCTTGTAGTGAAGTCTTGGAGTGTCATGAAGAAAAACTCAGCTGAATTAGG
TCTCAAACTCTTCATCAAGTAAGTAATGATCCCATTGATCTCTCTCTATTTTCTTTTTATGTATATAGTC
TGAGATATGAACTACTATTTTGAACTGTAGGATCTTTGAGATTGCACCAACAACGAAGAAGATGTTCTCT
TTCTTGAGAGACTCACCAATTCCTGCTGAGCAAATCCAAAGCTCAAGCCTCACGCAATGTCTGTTTTTG
TCATGGTAATAATCAATATCAAATAACATGATTTTGCTTATATATTCGAATCAAAGATTGTTGAGTTTTG
GGGTTTATTATCAGTGTTGTGAATCAGCAGTACAACTGAGGAAAACAGGGAAAGTTACGGTGAGGGAGAC
TACTTTGAAGAGACTTGGAGCCAGCCATTCTAAATACGGTGTCGTTGACGAACACTTTGAGGTTAGTAGT
TATTTGTCATATCTCAAAATGTTCTTTATCATACAAATATGTTAACTTGATTTTTTTTGGTTGATGTAAA
AATGATTTATAACTGCAGGTGGCCAAGTATGCATTGTTGGAGACGATAAAGGAGGCAGTGCCGGAGATGT
GGTCACCGGAGATGAAGGTGGCTTGGGGTCAGGCTTATGATCACCTTGTTGCTGCCATTAAAGCTGAAAT
GAATCTTTCCAACTAAAAAATCATATACTATTATATAGTTGTAAACTTGTAATAAATATTTCATTTTGAA
TTGTTCTCATGACTGTTGTTCTATTTGGTTTGGTTTGATTTAGTGACAATAATATATATATAGTGTGCAT
TCCAAAATCCTAATCATTTTGAATACAAGTTTCTTACTAATTGTTTTGCCCAAAAAAAAAATGTTTCTTA
CAAATTGTATTAAGATTATGATATTTTTGATAGACTTTAAAATAAATATAATTACTT'''

#A-U T-A G-C C-G

mrna = dnaseq.maketrans("ATGC","UACG")

# print(dnaseq.translate(mrna))

RNA_Codons = {
    # 'M' - start codon, '_' - stop codon

    'UUU': 'F',      'CUU': 'L',      'AUU': 'I',      'GUU': 'V',
    'UUC': 'F',      'CUC': 'L',      'AUC': 'I',      'GUC': 'V',
    'UUA': 'L',      'CUA': 'L',      'AUA': 'I',      'GUA': 'V',
    'UUG': 'L',      'CUG': 'L',      'AUG': 'M',      'GUG': 'V',
    'UCU': 'S',      'CCU': 'P',      'ACU': 'T',      'GCU': 'A',
    'UCC': 'S',      'CCC': 'P',      'ACC': 'T',      'GCC': 'A',
    'UCA': 'S',      'CCA': 'P',      'ACA': 'T',      'GCA': 'A',
    'UCG': 'S',      'CCG': 'P',      'ACG': 'T',      'GCG': 'A',
    'UAU': 'Y',      'CAU': 'H',      'AAU': 'N',      'GAU': 'D',
    'UAC': 'Y',      'CAC': 'H',      'AAC': 'N',      'GAC': 'D',
    'UAA': '_',      'CAA': 'Q',      'AAA': 'K',      'GAA': 'E',
    'UAG': '_',      'CAG': 'Q',      'AAG': 'K',      'GAG': 'E',
    'UGU': 'C',      'CGU': 'R',      'AGU': 'S',      'GGU': 'G',
    'UGC': 'C',      'CGC': 'R',      'AGC': 'S',      'GGC': 'G',
    'UGA': '_',      'CGA': 'R',      'AGA': 'R',      'GGA': 'G',
    'UGG': 'W',      'CGG': 'R',      'AGG': 'R',      'GGG': 'G',

    }

protein = ''

print(mrna)
for i in range(0, len(mrna),3):
    codon = mrna[i]
    protein += RNA_Codons[codon]
print(protein)

